class EventType:
    MARKET_DATA = "MARKET_DATA"

    MARKET_TICK = "MARKET_TICK"

    CANDLE = "CANDLE"

    SIGNAL = "SIGNAL"

    RISK_APPROVED = "RISK_APPROVED"

    ORDER_REQUEST = "ORDER_REQUEST"

    ORDER = "ORDER"

    ORDER_FILLED = "ORDER_FILLED"

    FILL = "FILL"

    POSITION = "POSITION"

    RISK_ALERT = "RISK_ALERT"

    REGIME = "REGIME"

    PORTFOLIO_SNAPSHOT = "PORTFOLIO_SNAPSHOT"

    EXECUTION_PLAN = "EXECUTION_PLAN"
